name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v4

      - name: Créer fichier .env
        run: |
          echo "MYSQL_HOST=mysql" >> .env
          echo "MONGODB_HOST=mongo" >> .env
          echo "MYSQL_DB_NAME=labo01_db" >> .env
          echo "DB_USERNAME=labo01po" >> .env
          echo "DB_PASSWORD=labo01" >> .env

      - name: Démarrer le conteneur
        run: |
          docker network create labo01-network
          docker compose build
          docker compose up -d

      - name: Attendre MySQL
        run: |
          sleep 10
          timeout=60
          until docker exec mysql mysqladmin ping -h localhost -u root -plabo01 --silent; do
            echo "Waiting for MySQL..."
            sleep 3
            timeout=$((timeout - 3))
            if [ $timeout -le 0 ]; then
              echo "MySQL failed to start"
              exit 1
            fi
          done
          sleep 5
      - name: Debug connexion MySQL
        run: docker exec store_manager_cli python -c "from daos.product_dao import ProductDAO; d = ProductDAO()"

      - name: Éxécuter les tests (TODO - ajouter test_products)
        run: docker exec store_manager_cli pytest src/tests/test_user.py src/tests/test_product.py

      - name: Cleanup
        if: always()
        run: docker compose down -v